pipeline:
  name: Sreeja-CD-Deploy
  identifier: SreejaCDDeploy
  projectIdentifier: terraform_project_sreeja
  orgIdentifier: training_13thNov
  tags: {}
  stages:
    - stage:
        name: Deploy
        identifier: Deploy
        description: "this is a git sync test"
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: k8s_service
          environment:
            environmentRef: org.dev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: dev_infra
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
